### ISSUE TITLE
no 'package.json'

### ISSUE THREAD

**Issue by kyeongsoo** [rosslh/rust-mandelbrot-set#2]
First of all, I do greatly appreciate your creating and sharing this nice code, which is an invaluable resource for my learning rust and wasm.

Today I tried to build & run it.
'cargo build' is just ok (only warning messages for non-snake case ID), but 'npm run start' results in the following error messages:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/kks/programming/rust/projects/rust-mandelbrot-set/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/kks/programming/rust/projects/rust-mandelbrot-set/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kks/.npm/_logs/2021-01-08T13_18_42_351Z-debug.log
kks@thinkpad-t495:~/programming/rust/projects/rust-mandelbrot-set$ npm run build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/kks/programming/rust/projects/rust-mandelbrot-set/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/kks/programming/rust/projects/rust-mandelbrot-set/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kks/.npm/_logs/2021-01-08T13_18_45_328Z-debug.log
```

I am a complete newbie and wonder whether the 'package.json' is missing in the repository by mistake or should be generated by another process.

Regards,
Joe

**Comment by rosslh** [comment]
Hey @kyeongsoo,

The package.json is in the `www/` directory. You'll also need to run `npm install` in that directory. I'll update the ReadMe tonight to make that clear. Does that help solve your problem?

**Comment by kyeongsoo** [comment]
> Hey @kyeongsoo,
> 
> The package.json is in the `www/` directory. You'll also need to run `npm install` in that directory. I'll update the ReadMe tonight to make that clear. Does that help solve your problem?

Yes, that solved the problem.
Great thanks for your prompt response!
