### ISSUE TITLE
Errors on `npm i`

### ISSUE THREAD

**Issue by jrkager** [rosslh/rust-mandelbrot-set#3]
I just first-time installed rust on my Mac (macOS Big Sur 11.1) an tried to install your webapp following the instructions. However, `npm i` doesn't run through without throwing errors. (and neither does `npm run build`) Since I'm new to rust and npm I'm having a hard time deciphering these. I add two screenshots
<img width="1396" alt="Screenshot 2021-01-20 at 01 49 13" src="https://user-images.githubusercontent.com/3820142/105111969-561f9e00-5ac2-11eb-8e40-f79d66fb7b8f.png">
<img width="1396" alt="Screenshot 2021-01-20 at 01 50 04" src="https://user-images.githubusercontent.com/3820142/105111981-5a4bbb80-5ac2-11eb-8963-dce9e7378701.png">

**Comment by rosslh** [comment]
Hi Johannes, can you try upgrading node to the latest version and let me know if that fixes it?

**Comment by jrkager** [comment]
That did the trick, thanks!
